[package]
name = "tempfile"
version = "2.2.0"
authors = ["Steven Allen <steven@stebalien.com>"]
description = "Securely create temporary files."

documentation = "https://stebalien.github.io/tempfile/tempfile/"
repository = "https://github.com/Stebalien/tempfile"
homepage = "http://stebalien.com/projects/tempfile-rs"
keywords = ["tempfile", "tmpfile", "filesystem"]
license = "MIT/Apache-2.0"

[dependencies]
rand = "0.4"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["fileapi", "winbase", "handleapi"] }

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.1"
